[package]
name = "beyond"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
beyond_derive = { version = "0.1.0", path = "../beyond_derive" }
serde = "1.0.219"
serde_json = "1.0.143"

[dev-dependencies]
serde = { version = "1.0.219", features = ["derive"] }
