[package]
name = "beyond_example"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
beyond = { version = "0.1.0", path = "../beyond" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
