[package]
name = "beyond_example"
version = "0.1.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/silvasch/beyond"

[dependencies]
beyond = { version = "0.1.0", path = "../beyond" }
serde = { version = "1.0.219", features = ["derive"] }
